//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleotic.DataContracts.CalculationEngine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BandValue
    {
        public int Id { get; set; }
        public int RuleTypeId { get; set; }
        public decimal BandMinValue { get; set; }
        public Nullable<decimal> BandMaxValue { get; set; }
        public decimal LoadingRate { get; set; }
        public int Version { get; set; }
        public Nullable<int> RuleAttributeId { get; set; }
        public Nullable<int> RuleExtensionId { get; set; }
    
        public virtual RuleType RuleType { get; set; }
        public virtual RuleTypeAttribute RuleTypeAttribute { get; set; }
        public virtual RuleTypeExtension RuleTypeExtension { get; set; }
    }
}
