//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleotic.DataContracts.CalculationEngine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrokerLoading
    {
        public int Id { get; set; }
        public Nullable<int> BrokerId { get; set; }
        public string BrokerName { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public bool IsLatest { get; set; }
        public decimal DiscretionaryDiscount { get; set; }
        public decimal LoadingRateMotor { get; set; }
        public decimal LoadingRateNonMotor { get; set; }
        public bool IsActive { get; set; }
        public decimal IncreasePercentageMotor { get; set; }
        public decimal IncreasePercentageNonMotor { get; set; }
    }
}
