//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleotic.DataContracts.CalculationEngine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimsHistoryLoading
    {
        public int Id { get; set; }
        public int ClaimPeriod { get; set; }
        public int NumberOfClaims { get; set; }
        public decimal LoadingRate { get; set; }
        public int Version { get; set; }
        public Nullable<int> RuleTypeId { get; set; }
    
        public virtual RuleType RuleType { get; set; }
    }
}
