//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleotic.DataContracts.CalculationEngine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyRuleConfiguration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PolicyRuleConfiguration()
        {
            this.PolicyRuleLoadings = new HashSet<PolicyRuleLoading>();
            this.PolicyRuleParameters = new HashSet<PolicyRuleParameter>();
        }
    
        public int Id { get; set; }
        public string PolicyNo { get; set; }
        public int RulesVersion { get; set; }
        public Nullable<decimal> BaseRate { get; set; }
        public Nullable<System.Guid> CallingContextId { get; set; }
        public System.DateTime DateCalculated { get; set; }
        public long RiskItemId { get; set; }
        public decimal BasicSumInsured { get; set; }
        public Nullable<decimal> CalculatedMonthlyPremium { get; set; }
        public Nullable<decimal> CalculatedRate { get; set; }
        public Nullable<decimal> CalculatedAnnualPremium { get; set; }
        public string RiskItemCoverType { get; set; }
        public string PostalCode { get; set; }
        public int BrokerId { get; set; }
        public Nullable<decimal> LoadedFactor { get; set; }
        public Nullable<decimal> AdditionalExcess { get; set; }
        public Nullable<decimal> DiscretionaryFloorAmount { get; set; }
        public string ProductType { get; set; }
        public bool DeclinedReferred { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolicyRuleLoading> PolicyRuleLoadings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PolicyRuleParameter> PolicyRuleParameters { get; set; }
    }
}
