//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleotic.DataContracts.CalculationEngine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyRuleLoading
    {
        public System.Guid Id { get; set; }
        public int PolicyRuleId { get; set; }
        public string LoadingName { get; set; }
        public decimal LoadingValue { get; set; }
        public bool IsAggregable { get; set; }
    
        public virtual PolicyRuleConfiguration PolicyRuleConfiguration { get; set; }
    }
}
