//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleotic.DataContracts.CalculationEngine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RuleType()
        {
            this.BandValues = new HashSet<BandValue>();
            this.RuleTypeExtensions = new HashSet<RuleTypeExtension>();
            this.RuleTypeAttributes = new HashSet<RuleTypeAttribute>();
            this.UnderwritingExclusions = new HashSet<UnderwritingExclusion>();
            this.ClaimsHistoryLoadings = new HashSet<ClaimsHistoryLoading>();
        }
    
        public int Id { get; set; }
        public string RuleName { get; set; }
        public bool IsEnabled { get; set; }
        public System.DateTime DateCreated { get; set; }
        public Nullable<System.DateTime> DateDeleted { get; set; }
        public System.DateTime EffectiveFrom { get; set; }
        public Nullable<System.DateTime> EffectiveTo { get; set; }
        public int Version { get; set; }
        public string CriteriaSource { get; set; }
        public string CalculationType { get; set; }
        public Nullable<int> EngineConfigurationId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BandValue> BandValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleTypeExtension> RuleTypeExtensions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RuleTypeAttribute> RuleTypeAttributes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnderwritingExclusion> UnderwritingExclusions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaimsHistoryLoading> ClaimsHistoryLoadings { get; set; }
        public virtual EngineConfiguration EngineConfiguration { get; set; }
    }
}
