//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nucleotic.DataContracts.CalculationEngine.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnderwritingExclusion
    {
        public int Id { get; set; }
        public int RuleTypeId { get; set; }
        public int Version { get; set; }
        public string MemberName { get; set; }
        public string Operator { get; set; }
        public string ExclusionValue { get; set; }
        public string Reason { get; set; }
        public Nullable<int> RuleTypeAttributeId { get; set; }
    
        public virtual RuleType RuleType { get; set; }
        public virtual RuleTypeAttribute RuleTypeAttribute { get; set; }
    }
}
